import { Routes } from '@angular/router';
import { authGuard } from './services/auth.guard';

export const routes: Routes = [
    { path: '', loadComponent: () => import('./platform/platform.component').then(m => m.PlatformComponent) },
    { path: 'settings', loadComponent: () => import('./settings/settings.component').then(m => m.SettingsComponent) },
    { path: 'stats', loadComponent: () => import('./stats/stats.component').then(m => m.StatsComponent) },
    { path: 'about', loadComponent: () => import('./about/about.component').then(m => m.AboutComponent) },
    { path: 'lehrplan', loadComponent: () => import('./lehrplan/lehrplan.component').then(m => m.LehrplanComponent) },
    { path: 'aehnlichewoerter', loadComponent: () => import('./apps/aehnlichewoerter/aehnlichewoerter.component').then(m => m.AehnlichewoerterComponent) },
    { path: 'oberbegriffe', loadComponent: () => import('./apps/oberbegriffe/oberbegriffe.component').then(m => m.OberbegriffeComponent) },
    { path: 'wortfamilie', loadComponent: () => import('./apps/wortfamilie/wortfamilie.component').then(m => m.WortfamilieComponent) },
    { path: 'kopfrechnen', loadComponent: () => import('./apps/kopfrechnen/kopfrechnen.component').then(m => m.KopfrechnenComponent) },
    { path: 'umrechnen', loadComponent: () => import('./apps/umrechnen/umrechnen.component').then(m => m.UmrechnenComponent) },
    { path: 'zeitrechnen', loadComponent: () => import('./apps/zeitrechnen/zeitrechnen.component').then(m => m.ZeitrechnenComponent) },
    { path: 'symmetry', loadComponent: () => import('./apps/symmetry/symmetry.component').then(m => m.SymmetryComponent) },
    { path: 'wortstaemme', loadComponent: () => import('./apps/wortstaemme/wortstaemme.component').then(m => m.WortstaemmeComponent) },
    { path: 'verben', loadComponent: () => import('./apps/verben/verben.component').then(m => m.VerbenComponent) },
    { path: 'kasus', loadComponent: () => import('./apps/kasus/kasus.component').then(m => m.KasusComponent) },
    { path: 'redewendungen', loadComponent: () => import('./apps/redewendungen/redewendungen.component').then(m => m.RedewendungenComponent) },
    { path: 'satzzeichen', loadComponent: () => import('./apps/satzzeichen/satzzeichen.component').then(m => m.SatzzeichenComponent) },
    { path: 'fehler', loadComponent: () => import('./apps/fehler/fehler.component').then(m => m.FehlerComponent) },
    { path: 'dasdass', loadComponent: () => import('./apps/dasdass/dasdass.component').then(m => m.DasdassComponent) },
    { path: 'textaufgaben', loadComponent: () => import('./apps/textaufgaben/textaufgaben.component').then(m => m.TextaufgabenComponent) },
    { path: 'symmetrien', loadComponent: () => import('./apps/symmetrien/symmetrien.component').then(m => m.SymmetrienComponent) },
    { path: 'isolation', loadComponent: () => import('./apps/isolation/isolation.component').then(m => m.IsolationComponent) },
    { path: 'quarto', loadComponent: () => import('./apps/quarto/quarto.component').then(m => m.QuartoComponent) },
    { path: 'wortarten', loadComponent: () => import('./apps/wortarten/wortarten.component').then(m => m.WortartenComponent) },
    { path: 'synant', loadComponent: () => import('./apps/synant/synant.component').then(m => m.SynantComponent) },
    { path: 'textverstaendnis', loadComponent: () => import('./apps/textverstaendnis/textverstaendnis.component').then(m => m.TextverstaendnisComponent) },
    { path: 'flaechenfinden', loadComponent: () => import('./apps/flaechenfinden/flaechenfinden.component').then(m => m.FlaechenfindenComponent) },
    { path: 'rechtschreibung', loadComponent: () => import('./apps/rechtschreibung/rechtschreibung.component').then(m => m.RechtschreibungComponent) },
    { path: 'brueche', loadComponent: () => import('./apps/brueche/brueche.component').then(m => m.BruecheComponent) },
    { path: 'komplexe-abbildung', loadComponent: () => import('./apps/komplexe-abbildung/komplexe-abbildung.component').then(m => m.KomplexeAbbildungComponent) },
    { path: 'einheitskreis', loadComponent: () => import('./apps/einheitskreis/einheitskreis.component').then(m => m.EinheitskreisComponent) },
    { path: 'vektoren', loadComponent: () => import('./apps/vektoren/vektoren').then(m => m.VektorenComponent) },
    { path: 'funktionen', loadComponent: () => import('./apps/funktionen/funktionen').then(m => m.FunktionenComponent) },
    { path: 'gleichungen', loadComponent: () => import('./apps/gleichungen/gleichungen.component').then(m => m.GleichungenComponent) },
    { path: 'admin/text-aufgaben', canActivate: [authGuard], loadComponent: () => import('./admin/text-aufgaben-admin/text-aufgaben-admin.component').then(m => m.TextAufgabenAdminComponent) },
    { path: 'admin/content', canActivate: [authGuard], loadComponent: () => import('./admin/content-editor/content-editor.component').then(m => m.ContentEditorComponent) },
    { path: 'admin/reading-review', canActivate: [authGuard], loadComponent: () => import('./admin/reading-review/reading-review.component').then(m => m.ReadingReviewComponent) },
    { path: 'admin', canActivate: [authGuard], loadComponent: () => import('./feedback-review/feedback-review').then(m => m.FeedbackReviewComponent) },
    { path: '**', redirectTo: '' }
];
